spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: sendOrderEvent
      group-id: gestioneComanda
    consumer:
      gestioneCucina:
        topic: notifyPrepEvent
        group-id: cucina
      gestioneCliente:
        topic: notifyOrderEvent
        group-id: cliente